# Copyright 2026 Statek authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Chat history items and per-item formatting for LLM API requests.

Defines a normalised representation of a single LLM chat history element
(``ChatHistoryItem``) together with the ``format_chat_history_item``
function that converts such an element into a provider-ready dict ready
for embedding in the LLM JSON request.

The formatting is provider-agnostic but matches the OpenAI / OpenRouter
message schema (which is also what Statek's OpenRouter LLM API uses):

    {"role": "system" | "user" | "assistant" | "tool", "content": ...}

with assistant tool-call messages using the OpenAI ``tool_calls`` array.
"""

# pylint: disable=no-member

import json
from dataclasses import dataclass
from typing import Dict, List, Optional, Union

import dbzero as db0

from statek.chat_style import ChatStyle
from statek.utils import CallSpec, strip_markup


@db0.enum(values=["SYSTEM", "USER", "ASSISTANT", "TOOL"])
class ChatRole:  # pylint: disable=too-few-public-methods
    """Role of a single chat history element.

    SYSTEM    - reserved for the system prompt
    USER      - either a real person or the Python runtime / console output
    ASSISTANT - LLM-originating turn (response or tool call request)
    TOOL      - the result of a single tool call
    """


@db0.enum(values=["SYSTEM", "USER", "ASSISTANT", "CONSOLE"])
class ContentSource:  # pylint: disable=too-few-public-methods
    """Origin of the ``content`` field in a chat history element.

    SYSTEM    - generated by Statek itself (e.g. system prompt, warmup code)
    USER      - written by a real user
    ASSISTANT - produced by the LLM
    CONSOLE   - captured from the Python runtime / tool execution
    """


@dataclass
class ChatHistoryItem:
    """A single, format-stripped element of an LLM chat history.

    Attributes:
        role: The chat role this element belongs to.
        content: The raw textual content (without any wrapping markdown
            or XML boxing).  ``None`` for pure tool-call requests.
        content_src: Where ``content`` originated from.  Required whenever
            ``content`` is not ``None``.
        tool_calls: Either a single ``CallSpec`` or a list of ``CallSpec``
            instances.  For ``ASSISTANT`` items this represents tool-call
            requests issued by the LLM.  For ``TOOL`` items it may
            optionally identify the call this item is the result of (the
            ``id`` of the (first) ``CallSpec`` is then used as the
            ``tool_call_id`` of the produced message).
    """
    role: "ChatRole"
    content: Optional[str] = None
    content_src: Optional["ContentSource"] = None
    tool_calls: Optional[Union[CallSpec, List[CallSpec]]] = None


def _wrap_console(content: str, style: "ChatStyle",
                  xml_tags: Optional[Dict[str, str]]) -> str:
    """Apply chat-style and xml-box wrapping to console-sourced content."""
    from statek.utils import _fmt_console_lines  # pylint: disable=import-outside-toplevel
    lines = content.split("\n") if content else []
    formatted = _fmt_console_lines(lines, style)
    tag = xml_tags.get("console") if xml_tags else None
    if tag:
        formatted = f"<{tag}>\n{formatted}\n</{tag}>"
    return formatted


def _wrap_python_code(code: str, style: "ChatStyle") -> str:
    """Wrap Python code in a ```python ...``` block unless DIRECT style."""
    if style == ChatStyle.DIRECT:
        return code
    return f"```python\n{code}\n```"


def _normalise_tool_calls(
    tool_calls: Union[CallSpec, List[CallSpec]],
) -> List[CallSpec]:
    """Return ``tool_calls`` as a list, accepting either a single CallSpec or a list."""
    if isinstance(tool_calls, CallSpec):
        return [tool_calls]
    return list(tool_calls)


def _json_default(obj):
    """Fallback encoder for ``json.dumps`` handling db0 persistent collections."""
    if isinstance(obj, (set, frozenset)):
        return list(obj)
    if hasattr(obj, "items") and callable(obj.items):
        return dict(obj.items())
    try:
        return list(obj)
    except TypeError as exc:
        raise TypeError(
            f"Object of type {obj.__class__.__name__} is not JSON serializable"
        ) from exc


def _format_tool_call(cs: CallSpec) -> Dict:
    """Convert a CallSpec to an OpenAI-format ``tool_calls`` entry.

    For ``python_cli`` tool calls, any markdown code fences in the ``code``
    argument are stripped — the python_cli tool expects raw Python code,
    optionally with comments, but never with code fences.
    """
    kwargs = dict(cs.kwargs) if cs.kwargs else {}
    if cs.func_name == "python_cli" and "code" in kwargs and isinstance(kwargs["code"], str):
        if "```" in kwargs["code"]:
            kwargs["code"] = strip_markup(kwargs["code"], strict=False)
    return {
        "id": cs.id,
        "type": "function",
        "function": {
            "name": cs.func_name,
            "arguments": json.dumps(kwargs, default=_json_default),
        },
    }


def format_chat_history_item(
    item: ChatHistoryItem,
    style: "ChatStyle",
    settings: Optional["object"] = None,
) -> Dict:
    """Format a single chat history element for embedding in an LLM request.

    The element is formatted as a single message dict in the OpenAI /
    OpenRouter chat-completions schema.  ``CONSOLE``-sourced content is
    wrapped in the configured XML console tag whenever it is set,
    regardless of chat style.  Python code is wrapped in a markdown
    ``python`` code fence for every chat style except ``DIRECT``.

    Args:
        item: the chat history item to format.
        style: the chat style to apply for formatting.
        settings: optional ``StatekSettings``.  When ``None``, the cached
            global settings are loaded via ``get_statek_settings``.

    Returns:
        A dict ready to be embedded into the LLM request payload.

    Raises:
        ValueError: when ``item`` is malformed (e.g. an ``ASSISTANT`` item
            with neither ``content`` nor ``tool_calls``, or a ``content``
            value without a ``content_src``).
    """
    if settings is None:
        from statek.settings import get_statek_settings  # pylint: disable=import-outside-toplevel
        settings = get_statek_settings()
    xml_tags = settings.get_xml_box_tags() if settings else None

    if item.content is not None and item.content_src is None:
        raise ValueError("ChatHistoryItem.content_src is required when content is not None")

    role = item.role

    if role == ChatRole.SYSTEM:
        return {"role": "system", "content": item.content or ""}

    if role == ChatRole.USER:
        content = item.content or ""
        if item.content_src == ContentSource.CONSOLE:
            content = _wrap_console(content, style, xml_tags)
        return {"role": "user", "content": content}

    if role == ChatRole.TOOL:
        content = item.content or ""
        if item.content_src == ContentSource.CONSOLE:
            content = _wrap_console(content, style, xml_tags)
        msg: Dict = {"role": "tool", "content": content}
        if item.tool_calls is not None:
            tcs = _normalise_tool_calls(item.tool_calls)
            if tcs:
                msg["tool_call_id"] = tcs[0].id
        return msg

    if role == ChatRole.ASSISTANT:
        if item.tool_calls is not None:
            tcs = _normalise_tool_calls(item.tool_calls)
            tool_calls_payload = [_format_tool_call(cs) for cs in tcs]
            content = item.content if item.content else None
            return {
                "role": "assistant",
                "content": content,
                "tool_calls": tool_calls_payload,
            }
        if item.content is None:
            raise ValueError(
                "ASSISTANT ChatHistoryItem must have either content or tool_calls"
            )
        # Both warmup blocks (content_src=SYSTEM) and LLM responses
        # (content_src=ASSISTANT) carry Python code that must be wrapped in
        # markdown fences for every style except DIRECT.  In DIRECT mode the
        # content is left as-is — for LLM responses the spec calls for plain
        # text in that case anyway.
        return {"role": "assistant", "content": _wrap_python_code(item.content, style)}

    raise ValueError(f"Unsupported ChatRole: {role!r}")
